sudo: false

language:
- cpp

compiler:
- clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake-3.11

before_install:
- pip install --user cpp-coveralls

script:
- cd llvm-runner
- cmake -H. -Bbuild
- cd build
- cmake --build .
- ./src/llvm-runner # run test

after_success:
- coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
  email: false