sudo: true

language:
- cpp

compiler:
- clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake

before_install:
- pip install --user cpp-coveralls

before_script:
- git clone git@github.com:Tencent/rapidjson.git
- cd rapidjson
- mkdir build 
- cd build
- cmake ..
- make install
- cd ..

script:
- cd llvm-runner
- cmake -H. -Bbuild
- cd build
- cmake --build .
- ./src/llvm-runner # run test

after_success:
- coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
  email: false