sudo: false

language:
- cpp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test

before_install:
- pip install --user cpp-coveralls
- sudo apt-get install -y qt5-default rapidjson-dev

script:
- cmake -H. -Bbuild
- cd build
- cmake --build .
- ./src/llvm-runner # run test

after_success:
- coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
  email: false